### ISSUE TITLE
SeasonsList: Sticky seasons can be hidden below nav when scrolling up

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#174]

**Comment by Winter3531** [comment]
It appears that this is already corrected when using the demo platform that seems to be running dev branch. Please advice @IRHM if this is incorrect?

**Comment by IRHM** [comment]
Hi @Winter3531, thanks for reaching out, just checked on beta/demo site, looks like I'm still getting the issue. Specifically, it is this:

When scrolling down, it is ok:
![image](https://github.com/sbondCo/Watcharr/assets/37304121/fd56612d-5fc1-4d26-aebf-737fa0850c9e)

Then when scrolling back up, the nav can cover the seasons:
![image](https://github.com/sbondCo/Watcharr/assets/37304121/eecc0ddb-bceb-4076-8a35-45839d0006f7)

**Comment by Winter3531** [comment]
Perhaps I misunderstood the issue you are looking to get resolved. You do not want the season to be covered by nav you want it to show below the nav bar?

**Comment by IRHM** [comment]
> Perhaps I misunderstood the issue you are looking to get resolved. You do not want the season to be covered by nav you want it to show below the nav bar?

Yep, that is correct, in the example above, the `Specials` season, should not be hidden by the nav bar when scrolling up.

I'm not sure how big of a problem this would be for users, but It looks like it might be annoying, since you would have to scroll down just to be able to click the first season if the nav is shown.

**Comment by Winter3531** [comment]
Ok I understand now.

**Comment by IRHM** [comment]
> Ok I understand now.

Cool, if you wanted to work on this, let me know, I can assign you.
